# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://sahibyar.github.io/
baseurl: /
title: Sahib Yar
author: Sahib Yar
description: Personal blog and resume
avatar: profile.jpg
email: sahibyaar@hotmail.com
github: sahibyar # username
twitter: sahibyaar
facebook: sahib.yar
instagram: sahibyar
youtube: user/sahibyaar
skype: sahibyaar?call
location: place/Siddique+Trade+Center/@31.5313433,74.3522983,15z/data=!4m5!3m4!1s0x0:0xee6f3c848c9e5341!8m2!3d31.5313433!4d74.3522983
linkedin: sahibyar
linkedin_url: https://www.linkedin.com/
phone: //+923366037321
quora: sahib-yar
stackoverflow: users/2949645/sahib-yar   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
