# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://sahibyar.github.io/
baseurl: /
title: Sahib Yar
author: Sahib Yar
description: Personal blog and resume
avatar: profile.jpg
email: sahibyaar@hotmail.com
github: sahibyar # username
twitter: sahibyaar
facebook: sahib.yar
youtube: user/sahibyaar
skype: sahibyaar?call
location: place/Abbasi+Business+Centre+Rawalpindi/@33.6519466,73.0718534,19z/data=!4m5!3m4!1s0x0:0x7cb026ddcaabd3a7!8m2!3d33.6516861!4d73.0719727
linkedin: sahibyar
phone: //+923366037321
quora: sahib-yar
stackoverflow: users/2949645/sahib-yar   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
